"""Baseline: the schema as of the pre-Alembic ``create_all()`` + inline-ALTER path.

Revision ID: 0001_baseline
Revises:
Create Date: 2026-09-08

This is the root revision. **Every later migration, in every phase, branches
from ``0001_baseline`` or from a revision that descends from it** — never from
another phase's migration. See ``migrations/README.md``.

Autogenerated from ``database.models`` against an empty Postgres 16 database and
verified to produce a byte-for-byte equivalent schema on SQLite: after
``alembic upgrade head`` on an empty database of either engine,
``alembic`` autogenerate reports no differences
(``tests/test_schema_discipline.py``).
"""
from alembic import op
import sqlalchemy as sa

import database.types

revision = '0001_baseline'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Legacy cleanup carried over from the inline-migration era (E4): Reddit was
    # retired at 465c835 and the model class deleted, but databases created
    # before that still carry the orphaned table. `create_all()` never removed
    # it; the old `_run_migrations()` did, and the baseline keeps doing so for
    # any database adopted through this revision.
    op.execute("DROP TABLE IF EXISTS reddit_sentiment")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('exchange', sa.String(length=40), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=160), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('beta', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=60), nullable=True),
    sa.Column('currency', sa.String(length=20), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.Column('profile_source', sa.String(length=40), nullable=True),
    sa.Column('updated_at', database.types.UtcDateTime(), nullable=True),
    sa.Column('expires_at', database.types.UtcDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_profiles_ticker'), 'company_profiles', ['ticker'], unique=True)
    op.create_table('discovered_tickers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('catalyst_summary', sa.Text(), nullable=True),
    sa.Column('catalyst_type', sa.String(length=50), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('direction_hint', sa.String(length=20), nullable=True),
    sa.Column('discovery_context', sa.Text(), nullable=True),
    sa.Column('model_used', sa.String(length=50), nullable=True),
    sa.Column('run_id', sa.String(length=50), nullable=True),
    sa.Column('progressed_to_pipeline', sa.Boolean(), nullable=True),
    sa.Column('pipeline_score', sa.Float(), nullable=True),
    sa.Column('discovered_at', database.types.UtcDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discovered_tickers_ticker'), 'discovered_tickers', ['ticker'], unique=False)
    op.create_table('historical_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('event_subtype', sa.String(length=120), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_timestamp', database.types.UtcDateTime(), nullable=True),
    sa.Column('event_timing', sa.String(length=20), nullable=True),
    sa.Column('polarity', sa.String(length=20), nullable=True),
    sa.Column('magnitude', sa.Float(), nullable=True),
    sa.Column('headline', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_domain', sa.String(length=160), nullable=True),
    sa.Column('source_type', sa.String(length=40), nullable=True),
    sa.Column('provider', sa.String(length=30), nullable=True),
    sa.Column('provider_query', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('dedupe_key', sa.String(length=64), nullable=False),
    sa.Column('embedding_json', sa.Text(), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.Column('created_at', database.types.UtcDateTime(), nullable=True),
    sa.Column('updated_at', database.types.UtcDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key', name='uq_historical_event_dedupe_key')
    )
    op.create_index('ix_historical_events_dedupe', 'historical_events', ['dedupe_key'], unique=False)
    op.create_index(op.f('ix_historical_events_dedupe_key'), 'historical_events', ['dedupe_key'], unique=True)
    op.create_index(op.f('ix_historical_events_event_type'), 'historical_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_historical_events_ticker'), 'historical_events', ['ticker'], unique=False)
    op.create_index('ix_historical_events_ticker_type_date', 'historical_events', ['ticker', 'event_type', 'event_date'], unique=False)
    op.create_index('ix_historical_events_type_date', 'historical_events', ['event_type', 'event_date'], unique=False)
    op.create_table('macro_regime',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('regime', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('position_size_multiplier', sa.Float(), nullable=True),
    sa.Column('max_positions', sa.Integer(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('raw_inputs', sa.Text(), nullable=True),
    sa.Column('created_at', database.types.UtcDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_macro_regime_date'), 'macro_regime', ['date'], unique=True)
    op.create_table('pattern_provider_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cache_key', sa.String(length=120), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=True),
    sa.Column('query', sa.Text(), nullable=True),
    sa.Column('filters_json', sa.Text(), nullable=True),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('created_at', database.types.UtcDateTime(), nullable=True),
    sa.Column('updated_at', database.types.UtcDateTime(), nullable=True),
    sa.Column('expires_at', database.types.UtcDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cache_key', name='uq_pattern_provider_cache_key')
    )
    op.create_index('ix_pattern_provider_cache_provider', 'pattern_provider_cache', ['provider', 'expires_at'], unique=False)
    op.create_table('pattern_search_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=80), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('setup_type', sa.String(length=80), nullable=True),
    sa.Column('catalyst_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('provider_plan_json', sa.Text(), nullable=True),
    sa.Column('queries_json', sa.Text(), nullable=True),
    sa.Column('peer_set_json', sa.Text(), nullable=True),
    sa.Column('result_counts_json', sa.Text(), nullable=True),
    sa.Column('cost_estimate', sa.Float(), nullable=True),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', database.types.UtcDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pattern_search_runs_run_id'), 'pattern_search_runs', ['run_id'], unique=False)
    op.create_index(op.f('ix_pattern_search_runs_ticker'), 'pattern_search_runs', ['ticker'], unique=False)
    op.create_index('ix_pattern_search_runs_ticker_created', 'pattern_search_runs', ['ticker', 'created_at'], unique=False)
    op.create_table('peer_edges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('target_ticker', sa.String(length=10), nullable=False),
    sa.Column('peer_ticker', sa.String(length=10), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=80), nullable=True),
    sa.Column('reasons_json', sa.Text(), nullable=True),
    sa.Column('as_of_date', sa.Date(), nullable=True),
    sa.Column('expires_at', database.types.UtcDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_ticker', 'peer_ticker', 'source', 'as_of_date', name='uq_peer_edge_source_date')
    )
    op.create_index('ix_peer_edges_peer', 'peer_edges', ['peer_ticker'], unique=False)
    op.create_index(op.f('ix_peer_edges_peer_ticker'), 'peer_edges', ['peer_ticker'], unique=False)
    op.create_index('ix_peer_edges_target', 'peer_edges', ['target_ticker'], unique=False)
    op.create_index(op.f('ix_peer_edges_target_ticker'), 'peer_edges', ['target_ticker'], unique=False)
    op.create_table('pipeline_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=80), nullable=False),
    sa.Column('trigger_source', sa.String(length=40), nullable=True),
    sa.Column('started_at', database.types.UtcDateTime(), nullable=True),
    sa.Column('ended_at', database.types.UtcDateTime(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('scanned_count', sa.Integer(), nullable=True),
    sa.Column('screened_count', sa.Integer(), nullable=True),
    sa.Column('researched_count', sa.Integer(), nullable=True),
    sa.Column('memos_generated', sa.Integer(), nullable=True),
    sa.Column('approved_count', sa.Integer(), nullable=True),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('cost_estimate', sa.Float(), nullable=True),
    sa.Column('degraded_stages', sa.Text(), nullable=True),
    sa.Column('errors_json', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', database.types.UtcDateTime(), nullable=True),
    sa.Column('updated_at', database.types.UtcDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_runs_run_id'), 'pipeline_runs', ['run_id'], unique=True)
    op.create_table('scored_candidates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=80), nullable=True),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('scored_at', database.types.UtcDateTime(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.Column('catalyst_score', sa.Float(), nullable=True),
    sa.Column('fundamental_score', sa.Float(), nullable=True),
    sa.Column('pattern_score', sa.Float(), nullable=True),
    sa.Column('pattern_status', sa.String(length=40), nullable=True),
    sa.Column('web_research_score', sa.Float(), nullable=True),
    sa.Column('direction', sa.String(length=20), nullable=True),
    sa.Column('regime', sa.String(length=20), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('suggested_stop', sa.Float(), nullable=True),
    sa.Column('target_1', sa.Float(), nullable=True),
    sa.Column('memo_generated', sa.Boolean(), nullable=True),
    sa.Column('paper_traded', sa.Boolean(), nullable=True),
    sa.Column('cohort', sa.String(length=20), nullable=True),
    sa.Column('ret_t1', sa.Float(), nullable=True),
    sa.Column('ret_t3', sa.Float(), nullable=True),
    sa.Column('ret_t5', sa.Float(), nullable=True),
    sa.Column('ret_t10', sa.Float(), nullable=True),
    sa.Column('ret_t20', sa.Float(), nullable=True),
    sa.Column('returns_computed_at', database.types.UtcDateTime(), nullable=True),
    sa.Column('created_at', database.types.UtcDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scored_candidates_returns_pending', 'scored_candidates', ['returns_computed_at', 'scored_at'], unique=False)
    op.create_index('ix_scored_candidates_run_id', 'scored_candidates', ['run_id'], unique=False)
    op.create_index(op.f('ix_scored_candidates_ticker'), 'scored_candidates', ['ticker'], unique=False)
    op.create_table('tickers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('in_universe', sa.Boolean(), nullable=True),
    sa.Column('added_at', database.types.UtcDateTime(), nullable=True),
    sa.Column('updated_at', database.types.UtcDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickers_symbol'), 'tickers', ['symbol'], unique=True)
    op.create_table('watchlist_tickers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('added_at', database.types.UtcDateTime(), nullable=True),
    sa.Column('deactivated_at', database.types.UtcDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_watchlist_active', 'watchlist_tickers', ['active'], unique=False)
    op.create_index(op.f('ix_watchlist_tickers_ticker'), 'watchlist_tickers', ['ticker'], unique=False)
    op.create_table('web_research_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cache_key', sa.String(length=120), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('research_date', sa.String(length=10), nullable=False),
    sa.Column('catalyst_hash', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=True),
    sa.Column('model_used', sa.String(length=80), nullable=True),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('created_at', database.types.UtcDateTime(), nullable=True),
    sa.Column('updated_at', database.types.UtcDateTime(), nullable=True),
    sa.Column('expires_at', database.types.UtcDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cache_key', name='uq_web_research_cache_key')
    )
    op.create_index('ix_web_research_cache_lookup', 'web_research_cache', ['ticker', 'research_date', 'catalyst_hash'], unique=False)
    op.create_table('catalysts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('catalyst_type', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('magnitude', sa.Integer(), nullable=True),
    sa.Column('direction', sa.String(length=20), nullable=True),
    sa.Column('expected_impact_low', sa.Float(), nullable=True),
    sa.Column('expected_impact_mid', sa.Float(), nullable=True),
    sa.Column('expected_impact_high', sa.Float(), nullable=True),
    sa.Column('time_horizon_days', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('raw_source', sa.Text(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('haiku_score', sa.Integer(), nullable=True),
    sa.Column('escalated', sa.Boolean(), nullable=True),
    sa.Column('detected_at', database.types.UtcDateTime(), nullable=True),
    sa.Column('run_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_contexts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('macro_regime', sa.String(length=20), nullable=True),
    sa.Column('vix_level', sa.Float(), nullable=True),
    sa.Column('sp500_distance_200ma', sa.Float(), nullable=True),
    sa.Column('sector_momentum_20d', sa.Float(), nullable=True),
    sa.Column('ticker_momentum_20d', sa.Float(), nullable=True),
    sa.Column('ticker_volatility_20d', sa.Float(), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('trailing_pe_ratio', sa.Float(), nullable=True),
    sa.Column('ev_sales', sa.Float(), nullable=True),
    sa.Column('valuation_source_filing_date', sa.Date(), nullable=True),
    sa.Column('pit_quality', sa.String(length=20), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.Column('computed_at', database.types.UtcDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['historical_events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', name='uq_event_context_event')
    )
    op.create_index(op.f('ix_event_contexts_event_id'), 'event_contexts', ['event_id'], unique=True)
    op.create_table('event_outcomes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('anchor_price', sa.Float(), nullable=True),
    sa.Column('anchor_trade_date', sa.Date(), nullable=True),
    sa.Column('return_t1', sa.Float(), nullable=True),
    sa.Column('return_t3', sa.Float(), nullable=True),
    sa.Column('return_t5', sa.Float(), nullable=True),
    sa.Column('return_t10', sa.Float(), nullable=True),
    sa.Column('return_t20', sa.Float(), nullable=True),
    sa.Column('return_t60', sa.Float(), nullable=True),
    sa.Column('abnormal_return_t5', sa.Float(), nullable=True),
    sa.Column('abnormal_return_t10', sa.Float(), nullable=True),
    sa.Column('abnormal_return_t20', sa.Float(), nullable=True),
    sa.Column('benchmark_symbol', sa.String(length=20), nullable=True),
    sa.Column('sector_benchmark_symbol', sa.String(length=20), nullable=True),
    sa.Column('max_drawdown_t20', sa.Float(), nullable=True),
    sa.Column('max_drawdown_day', sa.Integer(), nullable=True),
    sa.Column('volume_ratio_t1', sa.Float(), nullable=True),
    sa.Column('gap_pct', sa.Float(), nullable=True),
    sa.Column('matured_horizons_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('computed_at', database.types.UtcDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['historical_events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', name='uq_event_outcome_event')
    )
    op.create_index(op.f('ix_event_outcomes_event_id'), 'event_outcomes', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_outcomes_ticker'), 'event_outcomes', ['ticker'], unique=False)
    op.create_table('fundamentals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('balance_sheet_score', sa.Float(), nullable=True),
    sa.Column('valuation_score', sa.Float(), nullable=True),
    sa.Column('growth_score', sa.Float(), nullable=True),
    sa.Column('composite_score', sa.Float(), nullable=True),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.Column('peer_comparison', sa.Text(), nullable=True),
    sa.Column('flags', sa.Text(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('updated_at', database.types.UtcDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker_id', 'as_of_date', name='uq_fundamental_ticker_date')
    )
    op.create_table('historical_patterns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=True),
    sa.Column('setup_type', sa.String(length=60), nullable=False),
    sa.Column('event_date', sa.String(length=20), nullable=False),
    sa.Column('source_ticker', sa.String(length=10), nullable=False),
    sa.Column('is_peer', sa.Boolean(), nullable=True),
    sa.Column('beat_magnitude', sa.Float(), nullable=True),
    sa.Column('return_t5', sa.Float(), nullable=True),
    sa.Column('return_t10', sa.Float(), nullable=True),
    sa.Column('return_t15', sa.Float(), nullable=True),
    sa.Column('return_t20', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('max_drawdown_day', sa.Integer(), nullable=True),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.Column('created_at', database.types.UtcDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('setup_type', 'source_ticker', 'event_date', name='uq_pattern_event')
    )
    op.create_index('idx_patterns_lookup', 'historical_patterns', ['setup_type', 'source_ticker'], unique=False)
    op.create_table('memos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('composite_score', sa.Float(), nullable=True),
    sa.Column('classification', sa.String(length=20), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('trade_params', sa.Text(), nullable=True),
    sa.Column('signal_breakdown', sa.Text(), nullable=True),
    sa.Column('opus_critique', sa.Text(), nullable=True),
    sa.Column('memo_data_json', sa.Text(), nullable=True),
    sa.Column('thesis', sa.Text(), nullable=True),
    sa.Column('bear_case', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('operator_notes', sa.Text(), nullable=True),
    sa.Column('telegram_message_id', sa.Integer(), nullable=True),
    sa.Column('created_at', database.types.UtcDateTime(), nullable=True),
    sa.Column('responded_at', database.types.UtcDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_memos_created_at', 'memos', ['created_at'], unique=False)
    op.create_table('price_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('adj_close', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker_id', 'date', name='uq_price_ticker_date')
    )
    op.create_index('ix_price_ticker_date', 'price_data', ['ticker_id', 'date'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('agent_type', sa.String(length=30), nullable=False),
    sa.Column('run_id', sa.String(length=50), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('direction', sa.String(length=20), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('raw_output', sa.Text(), nullable=True),
    sa.Column('created_at', database.types.UtcDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_signal_ticker_agent_run', 'signals', ['ticker_id', 'agent_type', 'run_id'], unique=False)
    op.create_table('web_research',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('synthesis', sa.Text(), nullable=True),
    sa.Column('catalyst_context', sa.Text(), nullable=True),
    sa.Column('competitive_dynamics', sa.Text(), nullable=True),
    sa.Column('management_signals', sa.Text(), nullable=True),
    sa.Column('bull_bear_debate', sa.Text(), nullable=True),
    sa.Column('institutional_positioning', sa.Text(), nullable=True),
    sa.Column('key_finding', sa.Text(), nullable=True),
    sa.Column('information_score', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('direction', sa.String(length=20), nullable=True),
    sa.Column('sources_summary', sa.Text(), nullable=True),
    sa.Column('model_used', sa.String(length=50), nullable=True),
    sa.Column('run_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', database.types.UtcDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deep_research_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('memo_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('task_id', sa.String(length=200), nullable=True),
    sa.Column('provider', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('original_score', sa.Float(), nullable=True),
    sa.Column('research_report', sa.Text(), nullable=True),
    sa.Column('reevaluation_result', sa.Text(), nullable=True),
    sa.Column('updated_score', sa.Float(), nullable=True),
    sa.Column('updated_recommendation', sa.String(length=30), nullable=True),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('submitted_at', database.types.UtcDateTime(), nullable=True),
    sa.Column('completed_at', database.types.UtcDateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['memo_id'], ['memos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deep_research_requests_ticker'), 'deep_research_requests', ['ticker'], unique=False)
    op.create_table('historical_contexts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pattern_id', sa.Integer(), nullable=False),
    sa.Column('macro_regime', sa.String(length=20), nullable=True),
    sa.Column('vix_level', sa.Float(), nullable=True),
    sa.Column('fwd_pe_ratio', sa.Float(), nullable=True),
    sa.Column('momentum_20d', sa.Float(), nullable=True),
    sa.Column('sp500_distance_200ma', sa.Float(), nullable=True),
    sa.Column('created_at', database.types.UtcDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pattern_id'], ['historical_patterns.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pattern_id', name='uq_context_pattern')
    )
    op.create_index(op.f('ix_historical_contexts_pattern_id'), 'historical_contexts', ['pattern_id'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('memo_id', sa.Integer(), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('entry_date', database.types.UtcDateTime(), nullable=True),
    sa.Column('exit_date', database.types.UtcDateTime(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('target_1', sa.Float(), nullable=True),
    sa.Column('target_2', sa.Float(), nullable=True),
    sa.Column('position_pct', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('exit_reason', sa.String(length=30), nullable=True),
    sa.Column('pnl_pct', sa.Float(), nullable=True),
    sa.Column('pnl_absolute', sa.Float(), nullable=True),
    sa.Column('setup_type', sa.String(length=50), nullable=True),
    sa.Column('signal_scores', sa.Text(), nullable=True),
    sa.Column('regime_at_entry', sa.String(length=20), nullable=True),
    sa.Column('alpaca_entry_order_id', sa.String(length=100), nullable=True),
    sa.Column('alpaca_stop_order_id', sa.String(length=100), nullable=True),
    sa.Column('broker', sa.String(length=30), nullable=True),
    sa.Column('broker_account_id', sa.String(length=100), nullable=True),
    sa.Column('broker_order_id', sa.String(length=100), nullable=True),
    sa.Column('broker_stop_order_id', sa.String(length=100), nullable=True),
    sa.Column('broker_order_strategy', sa.String(length=50), nullable=True),
    sa.Column('order_review_json', sa.Text(), nullable=True),
    sa.Column('execution_mode', sa.String(length=20), nullable=True),
    sa.Column('requested_notional', sa.Float(), nullable=True),
    sa.Column('filled_notional', sa.Float(), nullable=True),
    sa.Column('operator_notes', sa.Text(), nullable=True),
    sa.Column('peak_price', sa.Float(), nullable=True),
    sa.Column('t1_hit', sa.Boolean(), nullable=True),
    sa.Column('t2_hit', sa.Boolean(), nullable=True),
    sa.Column('t1_approaching_sent', sa.Boolean(), nullable=True),
    sa.Column('time_warning_sent', sa.Boolean(), nullable=True),
    sa.Column('drawdown_alert_sent', sa.Boolean(), nullable=True),
    sa.Column('created_at', database.types.UtcDateTime(), nullable=True),
    sa.Column('updated_at', database.types.UtcDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['memo_id'], ['memos.id'], ),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trades_broker_status', 'trades', ['broker', 'status'], unique=False)
    op.create_index('ix_trades_status_created_at', 'trades', ['status', 'created_at'], unique=False)
    op.create_table('order_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=True),
    sa.Column('memo_id', sa.Integer(), nullable=True),
    sa.Column('broker', sa.String(length=30), nullable=True),
    sa.Column('account_id', sa.String(length=100), nullable=True),
    sa.Column('order_id', sa.String(length=100), nullable=True),
    sa.Column('event_type', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('notional', sa.Float(), nullable=True),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.Column('created_at', database.types.UtcDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['memo_id'], ['memos.id'], ),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_order_events_broker_order', 'order_events', ['broker', 'order_id'], unique=False)
    op.create_index('ix_order_events_created_at', 'order_events', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_order_events_created_at', table_name='order_events')
    op.drop_index('ix_order_events_broker_order', table_name='order_events')
    op.drop_table('order_events')
    op.drop_index('ix_trades_status_created_at', table_name='trades')
    op.drop_index('ix_trades_broker_status', table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_historical_contexts_pattern_id'), table_name='historical_contexts')
    op.drop_table('historical_contexts')
    op.drop_index(op.f('ix_deep_research_requests_ticker'), table_name='deep_research_requests')
    op.drop_table('deep_research_requests')
    op.drop_table('web_research')
    op.drop_index('ix_signal_ticker_agent_run', table_name='signals')
    op.drop_table('signals')
    op.drop_index('ix_price_ticker_date', table_name='price_data')
    op.drop_table('price_data')
    op.drop_index('ix_memos_created_at', table_name='memos')
    op.drop_table('memos')
    op.drop_index('idx_patterns_lookup', table_name='historical_patterns')
    op.drop_table('historical_patterns')
    op.drop_table('fundamentals')
    op.drop_index(op.f('ix_event_outcomes_ticker'), table_name='event_outcomes')
    op.drop_index(op.f('ix_event_outcomes_event_id'), table_name='event_outcomes')
    op.drop_table('event_outcomes')
    op.drop_index(op.f('ix_event_contexts_event_id'), table_name='event_contexts')
    op.drop_table('event_contexts')
    op.drop_table('catalysts')
    op.drop_index('ix_web_research_cache_lookup', table_name='web_research_cache')
    op.drop_table('web_research_cache')
    op.drop_index(op.f('ix_watchlist_tickers_ticker'), table_name='watchlist_tickers')
    op.drop_index('ix_watchlist_active', table_name='watchlist_tickers')
    op.drop_table('watchlist_tickers')
    op.drop_index(op.f('ix_tickers_symbol'), table_name='tickers')
    op.drop_table('tickers')
    op.drop_index(op.f('ix_scored_candidates_ticker'), table_name='scored_candidates')
    op.drop_index('ix_scored_candidates_run_id', table_name='scored_candidates')
    op.drop_index('ix_scored_candidates_returns_pending', table_name='scored_candidates')
    op.drop_table('scored_candidates')
    op.drop_index(op.f('ix_pipeline_runs_run_id'), table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    op.drop_index(op.f('ix_peer_edges_target_ticker'), table_name='peer_edges')
    op.drop_index('ix_peer_edges_target', table_name='peer_edges')
    op.drop_index(op.f('ix_peer_edges_peer_ticker'), table_name='peer_edges')
    op.drop_index('ix_peer_edges_peer', table_name='peer_edges')
    op.drop_table('peer_edges')
    op.drop_index('ix_pattern_search_runs_ticker_created', table_name='pattern_search_runs')
    op.drop_index(op.f('ix_pattern_search_runs_ticker'), table_name='pattern_search_runs')
    op.drop_index(op.f('ix_pattern_search_runs_run_id'), table_name='pattern_search_runs')
    op.drop_table('pattern_search_runs')
    op.drop_index('ix_pattern_provider_cache_provider', table_name='pattern_provider_cache')
    op.drop_table('pattern_provider_cache')
    op.drop_index(op.f('ix_macro_regime_date'), table_name='macro_regime')
    op.drop_table('macro_regime')
    op.drop_index('ix_historical_events_type_date', table_name='historical_events')
    op.drop_index('ix_historical_events_ticker_type_date', table_name='historical_events')
    op.drop_index(op.f('ix_historical_events_ticker'), table_name='historical_events')
    op.drop_index(op.f('ix_historical_events_event_type'), table_name='historical_events')
    op.drop_index(op.f('ix_historical_events_dedupe_key'), table_name='historical_events')
    op.drop_index('ix_historical_events_dedupe', table_name='historical_events')
    op.drop_table('historical_events')
    op.drop_index(op.f('ix_discovered_tickers_ticker'), table_name='discovered_tickers')
    op.drop_table('discovered_tickers')
    op.drop_index(op.f('ix_company_profiles_ticker'), table_name='company_profiles')
    op.drop_table('company_profiles')
    # ### end Alembic commands ###
