"""Add ``source_observations`` — the bitemporal source ledger.

Revision ID: 0002_source_observations
Revises: 0001_baseline
Create Date: 2026-09-09

Spec Q section 8 defines the table; Spec O section 2 adds ``precision`` and the
provenance class. Phase 3a is the first writer (SEC XBRL companyfacts, the
submissions acceptance timestamps, and the 8-K Item 2.02 index); Phase 3b reads
it and Phase 4 adds the remaining planes. It is built once, here, to serve both.

Branches directly from ``0001_baseline`` and carries no foreign key to any
other phase's table, so the integration merge revision is a no-op join.

The indexes exist for one query shape: ``known_at_utc <= t`` narrowed by entity
and fact type, which is what every point-in-time read does.
"""
from alembic import op
import sqlalchemy as sa

import database.types


revision = '0002_source_observations'
down_revision = '0001_baseline'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_observations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_trust', sa.String(length=30), nullable=False),
    sa.Column('accession', sa.String(length=40), nullable=True),
    sa.Column('entity_cik', sa.String(length=10), nullable=False),
    sa.Column('ticker_at_time', sa.String(length=20), nullable=True),
    sa.Column('fact_type', sa.String(length=80), nullable=False),
    sa.Column('value_numeric', sa.Float(), nullable=True),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('valid_at', database.types.UtcDateTime(), nullable=False),
    sa.Column('known_at_utc', database.types.UtcDateTime(), nullable=False),
    sa.Column('precision', sa.String(length=10), nullable=False),
    sa.Column('provenance_class', sa.String(length=30), nullable=False),
    sa.Column('replay_eligible', sa.Boolean(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('quality_warnings', sa.Text(), nullable=False),
    sa.Column('superseded_observation_id', sa.Integer(), nullable=True),
    sa.Column('ingested_at', database.types.UtcDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['superseded_observation_id'], ['source_observations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payload_hash', name='uq_source_obs_payload_hash')
    )
    with op.batch_alter_table('source_observations', schema=None) as batch_op:
        batch_op.create_index('ix_source_obs_entity_fact_known', ['entity_cik', 'fact_type', 'known_at_utc'], unique=False)
        batch_op.create_index('ix_source_obs_known_at', ['known_at_utc'], unique=False)
        batch_op.create_index('ix_source_obs_source_accession', ['source', 'accession'], unique=False)
        batch_op.create_index('ix_source_obs_ticker_fact_known', ['ticker_at_time', 'fact_type', 'known_at_utc'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source_observations', schema=None) as batch_op:
        batch_op.drop_index('ix_source_obs_ticker_fact_known')
        batch_op.drop_index('ix_source_obs_source_accession')
        batch_op.drop_index('ix_source_obs_known_at')
        batch_op.drop_index('ix_source_obs_entity_fact_known')

    op.drop_table('source_observations')
    # ### end Alembic commands ###
