"""Add the portfolio ledger — Spec L §3.

Revision ID: 0004_portfolio_ledger
Revises: 0003_merge_heads
Create Date: 2026-09-09

Seven tables, in one revision, branching from the current head on ``main``:

``brokerage_accounts``  broker, masked account id, account type, booking method,
                        ``agent_placeable``, the declared capability set, and the
                        last sync's id/time/error.
``holdings``            append-only positions with ``instrument_type``; a null
                        basis stays null.
``tax_lots``            broker lots where the broker exposes them, with the
                        per-account booking method.
``cash_balances``       settled vs unsettled cash plus the pending T+1 tranches.
``broker_orders``       every order at the broker, with ``origin`` recording
                        whether the system or the owner's app placed it.
``portfolio_snapshots`` the daily rollup plus beta, realized volatility, and the
                        max/average pairwise correlation, each with its lookback
                        and ``n``.
``exposure_tags``       exposure by narrative, attached by symbol.

No foreign key leaves this set, so the integration merge revision with Phase 2
is a no-op join. ``broker_orders.execution_id`` names
``strategy_trades.execution_id`` (Spec Q, Phase 5) as a plain string for that
reason: the column can be written before the table it refers to exists.
"""
from alembic import op
import sqlalchemy as sa

import database.types


revision = '0004_portfolio_ledger'
down_revision = '0003_merge_heads'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brokerage_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('broker', sa.String(length=40), nullable=False),
    sa.Column('external_account_id', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('account_type', sa.String(length=10), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('booking_method', sa.String(length=10), nullable=False),
    sa.Column('agent_placeable', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('capabilities_json', sa.Text(), nullable=False),
    sa.Column('capabilities_probed_at', database.types.UtcDateTime(), nullable=True),
    sa.Column('last_sync_id', sa.String(length=36), nullable=True),
    sa.Column('last_sync_at', database.types.UtcDateTime(), nullable=True),
    sa.Column('last_sync_error', sa.Text(), nullable=False),
    sa.Column('last_sync_error_at', database.types.UtcDateTime(), nullable=True),
    sa.Column('created_at', database.types.UtcDateTime(), nullable=False),
    sa.Column('updated_at', database.types.UtcDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('broker', 'external_account_id', name='uq_brokerage_account')
    )
    with op.batch_alter_table('brokerage_accounts', schema=None) as batch_op:
        batch_op.create_index('ix_brokerage_accounts_enabled', ['enabled'], unique=False)

    op.create_table('exposure_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('tag', sa.String(length=60), nullable=False),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('source_ref', sa.String(length=120), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', database.types.UtcDateTime(), nullable=False),
    sa.Column('retired_at', database.types.UtcDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'tag', 'source', name='uq_exposure_tag')
    )
    with op.batch_alter_table('exposure_tags', schema=None) as batch_op:
        batch_op.create_index('ix_exposure_tags_tag', ['tag'], unique=False)

    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('as_of_utc', database.types.UtcDateTime(), nullable=False),
    sa.Column('sync_id', sa.String(length=36), nullable=False),
    sa.Column('total_value', sa.Float(), nullable=True),
    sa.Column('cash_total', sa.Float(), nullable=True),
    sa.Column('settled_cash', sa.Float(), nullable=True),
    sa.Column('unsettled_cash', sa.Float(), nullable=True),
    sa.Column('gross_exposure', sa.Float(), nullable=True),
    sa.Column('net_exposure', sa.Float(), nullable=True),
    sa.Column('sector_weights_json', sa.Text(), nullable=False),
    sa.Column('name_weights_json', sa.Text(), nullable=False),
    sa.Column('largest_positions_json', sa.Text(), nullable=False),
    sa.Column('largest_position_weight', sa.Float(), nullable=True),
    sa.Column('concentration_hhi', sa.Float(), nullable=True),
    sa.Column('beta_60', sa.Float(), nullable=True),
    sa.Column('beta_60_n', sa.Integer(), nullable=True),
    sa.Column('beta_250', sa.Float(), nullable=True),
    sa.Column('beta_250_n', sa.Integer(), nullable=True),
    sa.Column('realized_volatility', sa.Float(), nullable=True),
    sa.Column('realized_volatility_n', sa.Integer(), nullable=True),
    sa.Column('max_pairwise_correlation', sa.Float(), nullable=True),
    sa.Column('avg_pairwise_correlation', sa.Float(), nullable=True),
    sa.Column('correlation_lookback_sessions', sa.Integer(), nullable=True),
    sa.Column('correlation_names', sa.Integer(), nullable=True),
    sa.Column('metrics_notes_json', sa.Text(), nullable=False),
    sa.Column('inputs_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', database.types.UtcDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_date', name='uq_portfolio_snapshot_date')
    )
    with op.batch_alter_table('portfolio_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_portfolio_snapshots_date', ['snapshot_date'], unique=False)

    op.create_table('broker_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('broker_order_id', sa.String(length=80), nullable=False),
    sa.Column('ref_id', sa.String(length=80), nullable=True),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('order_type', sa.String(length=20), nullable=False),
    sa.Column('time_in_force', sa.String(length=10), nullable=False),
    sa.Column('limit_price', sa.Float(), nullable=True),
    sa.Column('stop_price', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('submitted_at', database.types.UtcDateTime(), nullable=True),
    sa.Column('filled_at', database.types.UtcDateTime(), nullable=True),
    sa.Column('filled_quantity', sa.Float(), nullable=True),
    sa.Column('average_fill_price', sa.Float(), nullable=True),
    sa.Column('origin', sa.String(length=20), nullable=False),
    sa.Column('execution_id', sa.String(length=64), nullable=True),
    sa.Column('sync_id', sa.String(length=36), nullable=False),
    sa.Column('as_of_utc', database.types.UtcDateTime(), nullable=False),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('raw_json', sa.Text(), nullable=False),
    sa.Column('created_at', database.types.UtcDateTime(), nullable=False),
    sa.Column('updated_at', database.types.UtcDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['brokerage_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'broker_order_id', name='uq_broker_order')
    )
    with op.batch_alter_table('broker_orders', schema=None) as batch_op:
        batch_op.create_index('ix_broker_orders_account_status', ['account_id', 'status'], unique=False)
        batch_op.create_index('ix_broker_orders_symbol', ['symbol'], unique=False)

    op.create_table('cash_balances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sync_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('settled_cash', sa.Float(), nullable=True),
    sa.Column('unsettled_cash', sa.Float(), nullable=True),
    sa.Column('buying_power', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('pending_settlements_json', sa.Text(), nullable=False),
    sa.Column('as_of_utc', database.types.UtcDateTime(), nullable=False),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('superseded_at', database.types.UtcDateTime(), nullable=True),
    sa.Column('superseded_by_sync_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', database.types.UtcDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['brokerage_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cash_balances', schema=None) as batch_op:
        batch_op.create_index('ix_cash_balances_account_asof', ['account_id', 'as_of_utc'], unique=False)
        batch_op.create_index('ix_cash_balances_current', ['account_id', 'superseded_at'], unique=False)
        batch_op.create_index('ix_cash_balances_sync', ['sync_id'], unique=False)

    op.create_table('holdings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sync_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('instrument_type', sa.String(length=16), nullable=False),
    sa.Column('instrument_detail_json', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('average_cost', sa.Float(), nullable=True),
    sa.Column('cost_basis', sa.Float(), nullable=True),
    sa.Column('last_price', sa.Float(), nullable=True),
    sa.Column('market_value', sa.Float(), nullable=True),
    sa.Column('notional', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('as_of_utc', database.types.UtcDateTime(), nullable=False),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('superseded_at', database.types.UtcDateTime(), nullable=True),
    sa.Column('superseded_by_sync_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', database.types.UtcDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['brokerage_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.create_index('ix_holdings_account_symbol_asof', ['account_id', 'symbol', 'as_of_utc'], unique=False)
        batch_op.create_index('ix_holdings_current', ['account_id', 'superseded_at'], unique=False)
        batch_op.create_index('ix_holdings_sync', ['sync_id'], unique=False)

    op.create_table('tax_lots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sync_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('broker_lot_id', sa.String(length=64), nullable=True),
    sa.Column('open_date', sa.Date(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('cost_basis', sa.Float(), nullable=True),
    sa.Column('term', sa.String(length=10), nullable=False),
    sa.Column('booking_method', sa.String(length=10), nullable=False),
    sa.Column('as_of_utc', database.types.UtcDateTime(), nullable=False),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('superseded_at', database.types.UtcDateTime(), nullable=True),
    sa.Column('superseded_by_sync_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', database.types.UtcDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['brokerage_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tax_lots', schema=None) as batch_op:
        batch_op.create_index('ix_tax_lots_account_symbol', ['account_id', 'symbol'], unique=False)
        batch_op.create_index('ix_tax_lots_current', ['account_id', 'superseded_at'], unique=False)
        batch_op.create_index('ix_tax_lots_sync', ['sync_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tax_lots', schema=None) as batch_op:
        batch_op.drop_index('ix_tax_lots_sync')
        batch_op.drop_index('ix_tax_lots_current')
        batch_op.drop_index('ix_tax_lots_account_symbol')

    op.drop_table('tax_lots')
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.drop_index('ix_holdings_sync')
        batch_op.drop_index('ix_holdings_current')
        batch_op.drop_index('ix_holdings_account_symbol_asof')

    op.drop_table('holdings')
    with op.batch_alter_table('cash_balances', schema=None) as batch_op:
        batch_op.drop_index('ix_cash_balances_sync')
        batch_op.drop_index('ix_cash_balances_current')
        batch_op.drop_index('ix_cash_balances_account_asof')

    op.drop_table('cash_balances')
    with op.batch_alter_table('broker_orders', schema=None) as batch_op:
        batch_op.drop_index('ix_broker_orders_symbol')
        batch_op.drop_index('ix_broker_orders_account_status')

    op.drop_table('broker_orders')
    with op.batch_alter_table('portfolio_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_portfolio_snapshots_date')

    op.drop_table('portfolio_snapshots')
    with op.batch_alter_table('exposure_tags', schema=None) as batch_op:
        batch_op.drop_index('ix_exposure_tags_tag')

    op.drop_table('exposure_tags')
    with op.batch_alter_table('brokerage_accounts', schema=None) as batch_op:
        batch_op.drop_index('ix_brokerage_accounts_enabled')

    op.drop_table('brokerage_accounts')
    # ### end Alembic commands ###
