"""Research workspace — dossiers, theses, invalidators, journal, questions.

Revision ID: 0004_research_workspace
Revises: 0003_merge_heads
Create Date: 2026-09-09

Spec M §3 defines the six tables. They branch from the current head on main and
carry no foreign key outside this group, so the Phase 1 integration merge is a
no-op join (migrations/README.md).

Three CHECK constraints on ``theses`` are the DDL half of Spec M §4's
invalidator discipline. Both engines enforce CHECK, so there is no dialect
branch here:

* ``ck_theses_status`` — the five statuses and nothing else.
* ``ck_theses_probability_range`` — a probability is a probability.
* ``ck_theses_active_is_falsifiable`` — ``active`` requires a stated
  probability, a ``resolution_at``, and at least one machine-checkable
  invalidator, counted in the denormalised column because a CHECK cannot
  count rows in another table.

The application enforces the same rules first, with readable refusals
(``research_workspace/store.py``); these constraints are what stops a
hand-written ``UPDATE`` from producing an unfalsifiable active thesis.
"""
from alembic import op
import sqlalchemy as sa

import database.types


revision = '0004_research_workspace'
down_revision = '0003_merge_heads'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dossiers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=False),
    sa.Column('created_at', database.types.UtcDateTime(), nullable=False),
    sa.Column('updated_at', database.types.UtcDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', name='uq_dossiers_ticker')
    )
    with op.batch_alter_table('dossiers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dossiers_ticker'), ['ticker'], unique=False)

    op.create_table('research_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('asked_by', sa.String(length=120), nullable=False),
    sa.Column('answer_md', sa.Text(), nullable=False),
    sa.Column('answered_at', database.types.UtcDateTime(), nullable=True),
    sa.Column('created_at', database.types.UtcDateTime(), nullable=False),
    sa.CheckConstraint("status IN ('open','answered','abandoned')", name='ck_research_questions_status'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('research_questions', schema=None) as batch_op:
        batch_op.create_index('ix_research_questions_status', ['status'], unique=False)

    op.create_table('theses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('claim', sa.Text(), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=True),
    sa.Column('probability', sa.Float(), nullable=True),
    sa.Column('original_probability', sa.Float(), nullable=True),
    sa.Column('probability_history_json', sa.Text(), nullable=False),
    sa.Column('resolution_at', sa.Date(), nullable=True),
    sa.Column('resolution_observable', sa.Text(), nullable=False),
    sa.Column('argument_json', sa.Text(), nullable=False),
    sa.Column('bear_case', sa.Text(), nullable=False),
    sa.Column('bear_case_author', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('machine_checkable_invalidators', sa.Integer(), nullable=False),
    sa.Column('linked_position_ref', sa.String(length=120), nullable=False),
    sa.Column('position_opened_at', database.types.UtcDateTime(), nullable=True),
    sa.Column('cohort_answer_ids_json', sa.Text(), nullable=False),
    sa.Column('next_review_at', sa.Date(), nullable=True),
    sa.Column('author', sa.String(length=120), nullable=False),
    sa.Column('author_kind', sa.String(length=20), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=True),
    sa.Column('resolved_at', database.types.UtcDateTime(), nullable=True),
    sa.Column('close_reason', sa.String(length=40), nullable=False),
    sa.Column('created_at', database.types.UtcDateTime(), nullable=False),
    sa.Column('updated_at', database.types.UtcDateTime(), nullable=False),
    sa.Column('activated_at', database.types.UtcDateTime(), nullable=True),
    sa.Column('weakened_at', database.types.UtcDateTime(), nullable=True),
    sa.Column('closed_at', database.types.UtcDateTime(), nullable=True),
    sa.CheckConstraint("status <> 'active' OR (probability IS NOT NULL AND resolution_at IS NOT NULL AND machine_checkable_invalidators >= 1)", name='ck_theses_active_is_falsifiable'),
    sa.CheckConstraint("status IN ('draft','active','weakened','invalidated','closed')", name='ck_theses_status'),
    sa.CheckConstraint('probability IS NULL OR (probability >= 0.0 AND probability <= 1.0)', name='ck_theses_probability_range'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('theses', schema=None) as batch_op:
        batch_op.create_index('ix_theses_next_review', ['next_review_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_theses_ticker'), ['ticker'], unique=False)
        batch_op.create_index('ix_theses_ticker_status', ['ticker', 'status'], unique=False)

    op.create_table('decision_journal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('tickers', sa.String(length=200), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('thesis_id', sa.Integer(), nullable=True),
    sa.Column('thesis_hash', sa.String(length=64), nullable=False),
    sa.Column('cohort_answer_id', sa.String(length=120), nullable=False),
    sa.Column('cohort_evidence_hash', sa.String(length=64), nullable=False),
    sa.Column('budget', sa.String(length=20), nullable=False),
    sa.Column('sizing_rationale', sa.Text(), nullable=False),
    sa.Column('expected_holding_days', sa.Integer(), nullable=True),
    sa.Column('note_md', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=120), nullable=False),
    sa.Column('author_kind', sa.String(length=20), nullable=False),
    sa.Column('created_at', database.types.UtcDateTime(), nullable=False),
    sa.Column('outcome_note', sa.Text(), nullable=False),
    sa.Column('outcome_return_pct', sa.Float(), nullable=True),
    sa.Column('outcome_exit_reason', sa.String(length=80), nullable=False),
    sa.Column('outcome_matched_reason', sa.Boolean(), nullable=True),
    sa.Column('outcome_recorded_at', database.types.UtcDateTime(), nullable=True),
    sa.CheckConstraint("budget IN ('evidenced','discretionary')", name='ck_decision_journal_budget'),
    sa.CheckConstraint("decision IN ('opened','added','trimmed','closed','passed')", name='ck_decision_journal_decision'),
    sa.ForeignKeyConstraint(['thesis_id'], ['theses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('decision_journal', schema=None) as batch_op:
        batch_op.create_index('ix_decision_journal_occurred', ['occurred_on'], unique=False)
        batch_op.create_index('ix_decision_journal_tickers', ['tickers'], unique=False)

    op.create_table('dossier_sections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dossier_id', sa.Integer(), nullable=False),
    sa.Column('section_key', sa.String(length=80), nullable=False),
    sa.Column('body_md', sa.Text(), nullable=False),
    sa.Column('sources_json', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=120), nullable=False),
    sa.Column('author_kind', sa.String(length=20), nullable=False),
    sa.Column('unsourced', sa.Boolean(), nullable=False),
    sa.Column('human_authored', sa.Boolean(), nullable=False),
    sa.Column('supersedes_id', sa.Integer(), nullable=True),
    sa.Column('superseded', sa.Boolean(), nullable=False),
    sa.Column('created_at', database.types.UtcDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], ),
    sa.ForeignKeyConstraint(['supersedes_id'], ['dossier_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dossier_sections', schema=None) as batch_op:
        batch_op.create_index('ix_dossier_sections_created', ['dossier_id', 'created_at'], unique=False)
        batch_op.create_index('ix_dossier_sections_current', ['dossier_id', 'section_key', 'superseded'], unique=False)

    op.create_table('thesis_invalidators',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('thesis_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('params_json', sa.Text(), nullable=False),
    sa.Column('machine_checkable', sa.Boolean(), nullable=False),
    sa.Column('post_hoc', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('last_checked_at', database.types.UtcDateTime(), nullable=True),
    sa.Column('last_check_detail', sa.Text(), nullable=False),
    sa.Column('triggered_at', database.types.UtcDateTime(), nullable=True),
    sa.Column('triggered_reason', sa.Text(), nullable=False),
    sa.Column('created_at', database.types.UtcDateTime(), nullable=False),
    sa.Column('author', sa.String(length=120), nullable=False),
    sa.CheckConstraint("status IN ('armed','triggered','needs_human_review','retired')", name='ck_thesis_invalidators_status'),
    sa.CheckConstraint("type IN ('metric_threshold','price_level','event','time_decay','qualitative')", name='ck_thesis_invalidators_type'),
    sa.ForeignKeyConstraint(['thesis_id'], ['theses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('thesis_invalidators', schema=None) as batch_op:
        batch_op.create_index('ix_thesis_invalidators_thesis', ['thesis_id', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thesis_invalidators', schema=None) as batch_op:
        batch_op.drop_index('ix_thesis_invalidators_thesis')

    op.drop_table('thesis_invalidators')
    with op.batch_alter_table('dossier_sections', schema=None) as batch_op:
        batch_op.drop_index('ix_dossier_sections_current')
        batch_op.drop_index('ix_dossier_sections_created')

    op.drop_table('dossier_sections')
    with op.batch_alter_table('decision_journal', schema=None) as batch_op:
        batch_op.drop_index('ix_decision_journal_tickers')
        batch_op.drop_index('ix_decision_journal_occurred')

    op.drop_table('decision_journal')
    with op.batch_alter_table('theses', schema=None) as batch_op:
        batch_op.drop_index('ix_theses_ticker_status')
        batch_op.drop_index(batch_op.f('ix_theses_ticker'))
        batch_op.drop_index('ix_theses_next_review')

    op.drop_table('theses')
    with op.batch_alter_table('research_questions', schema=None) as batch_op:
        batch_op.drop_index('ix_research_questions_status')

    op.drop_table('research_questions')
    with op.batch_alter_table('dossiers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dossiers_ticker'))

    op.drop_table('dossiers')
    # ### end Alembic commands ###
