"""Strategy Lab — the eight experiment tables (Spec Q §8).

Revision ID: 0007_strategy_lab
Revises: 0006_merge_research_workspace
Create Date: 2026-09-09

The ninth table Spec Q lists, ``source_observations``, already exists
(``0002_source_observations``, Phase 3a). This revision adds the rest:
``strategy_versions``, ``experiments``, ``experiment_arms``,
``market_snapshots``, ``strategy_decisions``, ``strategy_trades``,
``experiment_metric_snapshots`` and ``promotion_events``.

Every foreign key here points inside this group. Snapshot rows reference
``source_observations`` ids as plain integers in a JSON column, and
``strategy_trades.execution_id`` is the plain value Phase 1's
``broker_orders.execution_id`` already carries, so the integration merge with
Phases 3c, 4 and P stays a no-op join (``migrations/README.md``).

Two partial unique indexes carry invariants a CHECK cannot express. Both
engines accept a ``WHERE`` clause on a unique index (SQLite >= 3.8.0,
Postgres), so the same DDL runs on both and is given per dialect only because
SQLAlchemy namespaces the keyword:

``uq_experiment_arms_single_live_champion``
    unique on ``mode`` where ``mode = 'live' AND status = 'active'``. Every row
    it indexes holds the same value in that column, so at most one can exist in
    the entire table: the one global live champion of Spec Q §3/§8. A unique
    index over a literal constant would say the same thing, but SQLite will not
    index a constant expression and a real column costs nothing.

``uq_strategy_trades_open_execution``
    unique on ``decision_id`` where the status is **not** terminal — at most one
    non-terminal execution per decision (Spec Q §12 invariant 6), held by the
    database rather than an in-process lock that a second worker or a restart
    would not see. Spelled as ``NOT IN`` the terminal states rather than ``IN``
    the non-terminal ones so that a future state added without a migration
    lands on the constrained side and fails closed.

``uq_experiment_arms_active`` makes arm activation idempotent: one active arm
per experiment, strategy version and mode.
"""
from alembic import op
import sqlalchemy as sa

import database.types


revision = '0007_strategy_lab'
down_revision = '0006_merge_research_workspace'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('hypothesis', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('universe_spec', sa.String(length=120), nullable=False),
    sa.Column('data_cutoff_utc', database.types.UtcDateTime(), nullable=True),
    sa.Column('primary_metric', sa.String(length=80), nullable=False),
    sa.Column('benchmarks_json', sa.Text(), nullable=False),
    sa.Column('guardrail_metrics_json', sa.Text(), nullable=False),
    sa.Column('start_criteria_json', sa.Text(), nullable=False),
    sa.Column('end_criteria_json', sa.Text(), nullable=False),
    sa.Column('preregistration_json', sa.Text(), nullable=False),
    sa.Column('planned_variants', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(length=120), nullable=False),
    sa.Column('owner_decision', sa.String(length=40), nullable=False),
    sa.Column('owner_decision_at', database.types.UtcDateTime(), nullable=True),
    sa.Column('owner_notes', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('registered_at', database.types.UtcDateTime(), nullable=True),
    sa.Column('started_at', database.types.UtcDateTime(), nullable=True),
    sa.Column('ended_at', database.types.UtcDateTime(), nullable=True),
    sa.Column('created_at', database.types.UtcDateTime(), nullable=False),
    sa.Column('updated_at', database.types.UtcDateTime(), nullable=False),
    sa.CheckConstraint("status IN ('cancelled','completed','draft','evaluating','paused','registered','running')", name='ck_experiments_status'),
    sa.CheckConstraint('planned_variants >= 1', name='ck_experiments_planned_variants'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_experiments_name')
    )
    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.create_index('ix_experiments_status', ['status'], unique=False)

    op.create_table('market_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=True),
    sa.Column('universe_version', sa.String(length=120), nullable=True),
    sa.Column('as_of_utc', database.types.UtcDateTime(), nullable=False),
    sa.Column('data_cutoff_utc', database.types.UtcDateTime(), nullable=False),
    sa.Column('normalized_inputs_json', sa.Text(), nullable=False),
    sa.Column('constituents_json', sa.Text(), nullable=False),
    sa.Column('source_observation_ids_json', sa.Text(), nullable=False),
    sa.Column('provenance_json', sa.Text(), nullable=False),
    sa.Column('data_quality_json', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', database.types.UtcDateTime(), nullable=False),
    sa.CheckConstraint("(scope = 'ticker' AND ticker IS NOT NULL) OR (scope = 'universe' AND ticker IS NULL)", name='ck_market_snapshots_scope_shape'),
    sa.CheckConstraint("scope IN ('ticker','universe')", name='ck_market_snapshots_scope'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash', name='uq_market_snapshots_content_hash')
    )
    with op.batch_alter_table('market_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_market_snapshots_scope_as_of', ['scope', 'as_of_utc'], unique=False)
        batch_op.create_index('ix_market_snapshots_ticker_as_of', ['ticker', 'as_of_utc'], unique=False)

    op.create_table('strategy_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('hypothesis', sa.Text(), nullable=False),
    sa.Column('universe', sa.String(length=80), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('required_snapshot_fields_json', sa.Text(), nullable=False),
    sa.Column('execution_policy_version', sa.String(length=80), nullable=False),
    sa.Column('expected_holding_days', sa.Integer(), nullable=False),
    sa.Column('max_data_staleness_seconds', sa.Integer(), nullable=False),
    sa.Column('historically_replayable', sa.Boolean(), nullable=False),
    sa.Column('replayability_reason', sa.Text(), nullable=False),
    sa.Column('implementation_manifest_json', sa.Text(), nullable=False),
    sa.Column('implementation_manifest_hash', sa.String(length=64), nullable=False),
    sa.Column('config_json', sa.Text(), nullable=False),
    sa.Column('dependencies_json', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', database.types.UtcDateTime(), nullable=False),
    sa.Column('updated_at', database.types.UtcDateTime(), nullable=False),
    sa.CheckConstraint("status IN ('draft','live_eligible','paper','retired','shadow')", name='ck_strategy_versions_status'),
    sa.CheckConstraint('expected_holding_days >= 1', name='ck_strategy_versions_holding_days'),
    sa.CheckConstraint('max_data_staleness_seconds >= 0', name='ck_strategy_versions_staleness'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', 'version', name='uq_strategy_versions_slug_version')
    )
    with op.batch_alter_table('strategy_versions', schema=None) as batch_op:
        batch_op.create_index('ix_strategy_versions_status', ['status'], unique=False)

    op.create_table('experiment_arms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('strategy_version_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('risk_budget', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('promoted_from_arm_id', sa.Integer(), nullable=True),
    sa.Column('started_at', database.types.UtcDateTime(), nullable=True),
    sa.Column('ended_at', database.types.UtcDateTime(), nullable=True),
    sa.Column('created_at', database.types.UtcDateTime(), nullable=False),
    sa.Column('updated_at', database.types.UtcDateTime(), nullable=False),
    sa.CheckConstraint("mode IN ('live','paper','shadow')", name='ck_experiment_arms_mode'),
    sa.CheckConstraint("status IN ('active','inactive','paused','retired')", name='ck_experiment_arms_status'),
    sa.CheckConstraint('risk_budget >= 0', name='ck_experiment_arms_risk_budget'),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.ForeignKeyConstraint(['promoted_from_arm_id'], ['experiment_arms.id'], ),
    sa.ForeignKeyConstraint(['strategy_version_id'], ['strategy_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('experiment_arms', schema=None) as batch_op:
        batch_op.create_index('ix_experiment_arms_experiment_status', ['experiment_id', 'status'], unique=False)
        batch_op.create_index('ix_experiment_arms_mode_status', ['mode', 'status'], unique=False)
        batch_op.create_index('uq_experiment_arms_active', ['experiment_id', 'strategy_version_id', 'mode'], unique=True, sqlite_where=sa.text("status = 'active'"), postgresql_where=sa.text("status = 'active'"))
        batch_op.create_index('uq_experiment_arms_single_live_champion', ['mode'], unique=True, sqlite_where=sa.text("mode = 'live' AND status = 'active'"), postgresql_where=sa.text("mode = 'live' AND status = 'active'"))

    op.create_table('experiment_metric_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('arm_id', sa.Integer(), nullable=False),
    sa.Column('evaluation_cutoff_utc', database.types.UtcDateTime(), nullable=False),
    sa.Column('n_decisions', sa.Integer(), nullable=False),
    sa.Column('n_matured', sa.Integer(), nullable=False),
    sa.Column('n_closed', sa.Integer(), nullable=False),
    sa.Column('exposure', sa.Float(), nullable=True),
    sa.Column('turnover', sa.Float(), nullable=True),
    sa.Column('return_after_costs', sa.Float(), nullable=True),
    sa.Column('benchmark', sa.String(length=80), nullable=False),
    sa.Column('benchmark_relative_return', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('profit_factor', sa.Float(), nullable=True),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('mean_r', sa.Float(), nullable=True),
    sa.Column('median_r', sa.Float(), nullable=True),
    sa.Column('uncertainty_json', sa.Text(), nullable=False),
    sa.Column('cost_assumptions_json', sa.Text(), nullable=False),
    sa.Column('warnings_json', sa.Text(), nullable=False),
    sa.Column('metrics_json', sa.Text(), nullable=False),
    sa.Column('warnings_acknowledged', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_by', sa.String(length=120), nullable=False),
    sa.Column('acknowledged_at', database.types.UtcDateTime(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', database.types.UtcDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['arm_id'], ['experiment_arms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('arm_id', 'evaluation_cutoff_utc', name='uq_experiment_metric_snapshots_arm_cutoff')
    )
    with op.batch_alter_table('experiment_metric_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_experiment_metric_snapshots_arm', ['arm_id', 'evaluation_cutoff_utc'], unique=False)

    op.create_table('strategy_decisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('arm_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('reason_codes_json', sa.Text(), nullable=False),
    sa.Column('signal_strength', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('decision_json', sa.Text(), nullable=False),
    sa.Column('decision_hash', sa.String(length=64), nullable=False),
    sa.Column('blocked_reasons_json', sa.Text(), nullable=False),
    sa.Column('created_at', database.types.UtcDateTime(), nullable=False),
    sa.CheckConstraint("action IN ('abstain','flat','long')", name='ck_strategy_decisions_action'),
    sa.CheckConstraint("ticker <> ''", name='ck_strategy_decisions_ticker_present'),
    sa.ForeignKeyConstraint(['arm_id'], ['experiment_arms.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['market_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('arm_id', 'snapshot_id', 'ticker', name='uq_strategy_decisions_arm_snapshot_ticker')
    )
    with op.batch_alter_table('strategy_decisions', schema=None) as batch_op:
        batch_op.create_index('ix_strategy_decisions_arm_created', ['arm_id', 'created_at'], unique=False)
        batch_op.create_index('ix_strategy_decisions_hash', ['decision_hash'], unique=False)

    op.create_table('promotion_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_arm_id', sa.Integer(), nullable=False),
    sa.Column('target_arm_id', sa.Integer(), nullable=False),
    sa.Column('strategy_version_id', sa.Integer(), nullable=False),
    sa.Column('evidence_metric_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('from_mode', sa.String(length=20), nullable=False),
    sa.Column('to_mode', sa.String(length=20), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('owner', sa.String(length=120), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('previous_risk_budget', sa.Float(), nullable=False),
    sa.Column('new_risk_budget', sa.Float(), nullable=False),
    sa.Column('created_at', database.types.UtcDateTime(), nullable=False),
    sa.CheckConstraint("from_mode IN ('live','paper','shadow')", name='ck_promotion_events_from_mode'),
    sa.CheckConstraint("kind IN ('demotion','promotion')", name='ck_promotion_events_kind'),
    sa.CheckConstraint("to_mode IN ('live','paper','shadow')", name='ck_promotion_events_to_mode'),
    sa.CheckConstraint('source_arm_id <> target_arm_id', name='ck_promotion_events_distinct_arms'),
    sa.ForeignKeyConstraint(['evidence_metric_snapshot_id'], ['experiment_metric_snapshots.id'], ),
    sa.ForeignKeyConstraint(['source_arm_id'], ['experiment_arms.id'], ),
    sa.ForeignKeyConstraint(['strategy_version_id'], ['strategy_versions.id'], ),
    sa.ForeignKeyConstraint(['target_arm_id'], ['experiment_arms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('promotion_events', schema=None) as batch_op:
        batch_op.create_index('ix_promotion_events_source', ['source_arm_id', 'created_at'], unique=False)
        batch_op.create_index('ix_promotion_events_target', ['target_arm_id', 'created_at'], unique=False)

    op.create_table('strategy_trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('execution_id', sa.String(length=64), nullable=False),
    sa.Column('arm_id', sa.Integer(), nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('portfolio_context_hash', sa.String(length=64), nullable=False),
    sa.Column('legacy_trade_id', sa.Integer(), nullable=True),
    sa.Column('intended_entry_price', sa.Float(), nullable=True),
    sa.Column('filled_entry_price', sa.Float(), nullable=True),
    sa.Column('stop_price', sa.Float(), nullable=True),
    sa.Column('target1_price', sa.Float(), nullable=True),
    sa.Column('target2_price', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('notional', sa.Float(), nullable=True),
    sa.Column('costs', sa.Float(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('realized_pnl', sa.Float(), nullable=True),
    sa.Column('exit_reason', sa.String(length=40), nullable=False),
    sa.Column('blocked_reason', sa.String(length=80), nullable=False),
    sa.Column('reconciliation_state', sa.String(length=30), nullable=False),
    sa.Column('proposed_at', database.types.UtcDateTime(), nullable=True),
    sa.Column('approved_at', database.types.UtcDateTime(), nullable=True),
    sa.Column('submitted_at', database.types.UtcDateTime(), nullable=True),
    sa.Column('filled_at', database.types.UtcDateTime(), nullable=True),
    sa.Column('closed_at', database.types.UtcDateTime(), nullable=True),
    sa.Column('created_at', database.types.UtcDateTime(), nullable=False),
    sa.Column('updated_at', database.types.UtcDateTime(), nullable=False),
    sa.CheckConstraint("mode IN ('live','paper','shadow')", name='ck_strategy_trades_mode'),
    sa.CheckConstraint("status IN ('accepted','cancelled','closed','closing','expired','failed_no_order','filled','order_rejected','owner_approved','owner_rejected','partially_filled','placement_unknown','proposed','protected','protection_failed','protection_pending','reconciliation_required','review_rejected','risk_rejected','risk_reserved','submitted')", name='ck_strategy_trades_status'),
    sa.ForeignKeyConstraint(['arm_id'], ['experiment_arms.id'], ),
    sa.ForeignKeyConstraint(['decision_id'], ['strategy_decisions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('execution_id', name='uq_strategy_trades_execution_id')
    )
    with op.batch_alter_table('strategy_trades', schema=None) as batch_op:
        batch_op.create_index('ix_strategy_trades_arm_status', ['arm_id', 'status'], unique=False)
        batch_op.create_index('ix_strategy_trades_status', ['status'], unique=False)
        batch_op.create_index('uq_strategy_trades_open_execution', ['decision_id'], unique=True, sqlite_where=sa.text("status NOT IN ('cancelled','closed','expired','failed_no_order','order_rejected','owner_rejected','review_rejected','risk_rejected')"), postgresql_where=sa.text("status NOT IN ('cancelled','closed','expired','failed_no_order','order_rejected','owner_rejected','review_rejected','risk_rejected')"))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strategy_trades', schema=None) as batch_op:
        batch_op.drop_index('uq_strategy_trades_open_execution', sqlite_where=sa.text("status NOT IN ('cancelled','closed','expired','failed_no_order','order_rejected','owner_rejected','review_rejected','risk_rejected')"), postgresql_where=sa.text("status NOT IN ('cancelled','closed','expired','failed_no_order','order_rejected','owner_rejected','review_rejected','risk_rejected')"))
        batch_op.drop_index('ix_strategy_trades_status')
        batch_op.drop_index('ix_strategy_trades_arm_status')

    op.drop_table('strategy_trades')
    with op.batch_alter_table('promotion_events', schema=None) as batch_op:
        batch_op.drop_index('ix_promotion_events_target')
        batch_op.drop_index('ix_promotion_events_source')

    op.drop_table('promotion_events')
    with op.batch_alter_table('strategy_decisions', schema=None) as batch_op:
        batch_op.drop_index('ix_strategy_decisions_hash')
        batch_op.drop_index('ix_strategy_decisions_arm_created')

    op.drop_table('strategy_decisions')
    with op.batch_alter_table('experiment_metric_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_experiment_metric_snapshots_arm')

    op.drop_table('experiment_metric_snapshots')
    with op.batch_alter_table('experiment_arms', schema=None) as batch_op:
        batch_op.drop_index('uq_experiment_arms_single_live_champion', sqlite_where=sa.text("mode = 'live' AND status = 'active'"), postgresql_where=sa.text("mode = 'live' AND status = 'active'"))
        batch_op.drop_index('uq_experiment_arms_active', sqlite_where=sa.text("status = 'active'"), postgresql_where=sa.text("status = 'active'"))
        batch_op.drop_index('ix_experiment_arms_mode_status')
        batch_op.drop_index('ix_experiment_arms_experiment_status')

    op.drop_table('experiment_arms')
    with op.batch_alter_table('strategy_versions', schema=None) as batch_op:
        batch_op.drop_index('ix_strategy_versions_status')

    op.drop_table('strategy_versions')
    with op.batch_alter_table('market_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_market_snapshots_ticker_as_of')
        batch_op.drop_index('ix_market_snapshots_scope_as_of')

    op.drop_table('market_snapshots')
    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.drop_index('ix_experiments_status')

    op.drop_table('experiments')
    # ### end Alembic commands ###
