"""Phase 6 — the proposal -> approval -> execution lifecycle (Spec L §6).

Revision ID: 0009_execution_lifecycle
Revises: 0008_merge_strategy_lab
Create Date: 2026-09-09

Two tables.

``proposals``
    one ``propose_order`` call and everything that happened to it: what was
    asked for, what every guard said, the size **code** computed from
    ``entry``, ``stop`` and ``risk_fraction`` (Spec L §6.6 — an agent never
    chooses a quantity), each cap that bound that size, the portfolio context
    hash it was computed against, the signed single-use owner approval that
    released it, and the entry and stop orders that resulted.

``execution_kill_switch``
    one row. A kill switch that lives in a process variable is not a kill
    switch: the thing it has to survive is the restart after the incident
    (Spec L §6.5, Spec Q §12 invariant 9).

No foreign keys leave this revision. ``cohort_answer_id`` (Spec N),
``execution_id`` (``strategy_trades``, Spec Q) and ``account_id``
(``brokerage_accounts``, Phase 1) are all recorded as plain values, because a
cross-phase FK makes the integration merge non-trivial (``migrations/README.md``)
and none of the three is owned by this phase.

Three CHECK constraints carry invariants that are cheaper to hold in the
database than to re-assert at every call site: the status vocabulary, the
budget vocabulary, and ``side = 'long'`` — Spec L §6 never describes a short
entry's protective shape, so the schema refuses one rather than leaving it to
a code path nobody has written. ``quantity >= 0`` is the fourth: the size is
rounded **down** to whole shares and a zero is ``risk_rejected``, never
rounded up.
"""
from alembic import op
import sqlalchemy as sa

import database.types


revision = '0009_execution_lifecycle'
down_revision = '0008_merge_strategy_lab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execution_kill_switch',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('engaged', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('changed_by', sa.String(length=64), nullable=False),
    sa.Column('engaged_at', database.types.UtcDateTime(), nullable=True),
    sa.Column('released_at', database.types.UtcDateTime(), nullable=True),
    sa.Column('updated_at', database.types.UtcDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proposals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('proposal_uid', sa.String(length=36), nullable=False),
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('entry', sa.Float(), nullable=False),
    sa.Column('stop', sa.Float(), nullable=False),
    sa.Column('expected_hold_sessions', sa.Integer(), nullable=True),
    sa.Column('risk_fraction', sa.Float(), nullable=False),
    sa.Column('risk_fraction_effective', sa.Float(), nullable=False),
    sa.Column('cohort_answer_id', sa.String(length=120), nullable=True),
    sa.Column('budget', sa.String(length=20), nullable=False),
    sa.Column('evidence_lower_bound', sa.Float(), nullable=True),
    sa.Column('evidence_point_estimate', sa.Float(), nullable=True),
    sa.Column('evidence_horizon_sessions', sa.Integer(), nullable=True),
    sa.Column('evidence_multiplier', sa.Float(), nullable=True),
    sa.Column('evidence_gate_mode', sa.String(length=20), nullable=False),
    sa.Column('evidence_reason', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('notional', sa.Float(), nullable=False),
    sa.Column('risk_dollars', sa.Float(), nullable=False),
    sa.Column('equity_at_proposal', sa.Float(), nullable=False),
    sa.Column('caps_json', sa.Text(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('account_label', sa.String(length=100), nullable=False),
    sa.Column('execution_mode', sa.String(length=20), nullable=False),
    sa.Column('portfolio_context_hash', sa.String(length=64), nullable=False),
    sa.Column('ledger_as_of_utc', database.types.UtcDateTime(), nullable=True),
    sa.Column('requester_token_label', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('rejection_code', sa.String(length=60), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=False),
    sa.Column('card_md', sa.Text(), nullable=False),
    sa.Column('approval_nonce', sa.String(length=32), nullable=True),
    sa.Column('approval_signature', sa.String(length=64), nullable=True),
    sa.Column('approval_expires_at', database.types.UtcDateTime(), nullable=True),
    sa.Column('approval_owner_id', sa.String(length=64), nullable=False),
    sa.Column('approval_consumed_at', database.types.UtcDateTime(), nullable=True),
    sa.Column('approved_at', database.types.UtcDateTime(), nullable=True),
    sa.Column('entry_ref_id', sa.String(length=80), nullable=True),
    sa.Column('entry_broker_order_id', sa.String(length=80), nullable=True),
    sa.Column('stop_ref_id', sa.String(length=80), nullable=True),
    sa.Column('stop_broker_order_id', sa.String(length=80), nullable=True),
    sa.Column('execution_id', sa.String(length=64), nullable=True),
    sa.Column('submitted_at', database.types.UtcDateTime(), nullable=True),
    sa.Column('filled_at', database.types.UtcDateTime(), nullable=True),
    sa.Column('filled_quantity', sa.Float(), nullable=True),
    sa.Column('average_fill_price', sa.Float(), nullable=True),
    sa.Column('protection_deadline_at', database.types.UtcDateTime(), nullable=True),
    sa.Column('protection_verified_at', database.types.UtcDateTime(), nullable=True),
    sa.Column('stop_replaced_count', sa.Integer(), nullable=False),
    sa.Column('created_at', database.types.UtcDateTime(), nullable=False),
    sa.Column('updated_at', database.types.UtcDateTime(), nullable=False),
    sa.CheckConstraint("budget IN ('discretionary','evidenced')", name='ck_proposals_budget'),
    sa.CheckConstraint("side = 'long'", name='ck_proposals_side_long_only'),
    sa.CheckConstraint("status IN ('approved','cancelled','expired','failed','filled','proposed','protected','reconciliation_required','rejected','risk_rejected','submitted','unprotected')", name='ck_proposals_status'),
    sa.CheckConstraint('quantity >= 0', name='ck_proposals_quantity_nonnegative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proposal_uid', name='uq_proposals_uid')
    )
    with op.batch_alter_table('proposals', schema=None) as batch_op:
        batch_op.create_index('ix_proposals_budget_created', ['budget', 'created_at'], unique=False)
        batch_op.create_index('ix_proposals_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index('ix_proposals_ticker', ['ticker'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proposals', schema=None) as batch_op:
        batch_op.drop_index('ix_proposals_ticker')
        batch_op.drop_index('ix_proposals_status_created')
        batch_op.drop_index('ix_proposals_budget_created')

    op.drop_table('proposals')
    op.drop_table('execution_kill_switch')
    # ### end Alembic commands ###
