"""Price plane: securities, price_bars, corporate_actions, universe_membership, price_snapshots.

Revision ID: 3p01_price_plane
Revises: 0001_baseline
Create Date: 2026-09-09

Phase 3p (Spec N §4.2/§4.3). **Branches directly from ``0001_baseline``**, as
``migrations/README.md`` requires — Phases 0b and 3a are adding their own tables
from the same parent in parallel, so a merge revision at integration is expected
and none of these tables carries a foreign key across a phase boundary.

The revision id is deliberately not ``0002``: three phases numbering their first
revision ``0002`` independently would collide in the same directory. ``3p01`` is
"phase 3p, revision 1".

Autogenerated from ``database.models`` and then reviewed: the only hand edit is
the ``import database.types`` that autogenerate omits (it renders
``database.types.UtcDateTime()`` without emitting the import) — the same edit
``0001_baseline`` carries.
"""
from alembic import op
import sqlalchemy as sa

import database.types

revision = '3p01_price_plane'
down_revision = '0001_baseline'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corporate_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('security_uid', sa.String(length=64), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('ex_date', sa.Date(), nullable=False),
    sa.Column('action_type', sa.String(length=32), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('ingested_at', database.types.UtcDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('security_uid', 'ex_date', 'action_type', 'source', name='uq_corporate_actions_uid_date_type_source')
    )
    with op.batch_alter_table('corporate_actions', schema=None) as batch_op:
        batch_op.create_index('ix_corporate_actions_uid_date', ['security_uid', 'ex_date'], unique=False)

    op.create_table('price_bars',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('security_uid', sa.String(length=64), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('raw_open', sa.Float(), nullable=False),
    sa.Column('raw_high', sa.Float(), nullable=False),
    sa.Column('raw_low', sa.Float(), nullable=False),
    sa.Column('raw_close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('split_factor', sa.Float(), nullable=False),
    sa.Column('dividend_cash', sa.Float(), nullable=False),
    sa.Column('split_adjusted_close', sa.Float(), nullable=False),
    sa.Column('total_return_close', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('ingested_at', database.types.UtcDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('security_uid', 'session_date', name='uq_price_bars_uid_date')
    )
    with op.batch_alter_table('price_bars', schema=None) as batch_op:
        batch_op.create_index('ix_price_bars_date', ['session_date'], unique=False)
        batch_op.create_index('ix_price_bars_uid_date', ['security_uid', 'session_date'], unique=False)

    op.create_table('price_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_slug', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('coverage_summary_json', sa.Text(), nullable=False),
    sa.Column('delisting_audit_json', sa.Text(), nullable=False),
    sa.Column('created_at', database.types.UtcDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_slug', name='uq_price_snapshots_slug')
    )
    op.create_table('securities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('security_uid', sa.String(length=64), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('ticker_valid_from', sa.Date(), nullable=True),
    sa.Column('ticker_valid_to', sa.Date(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('exchange', sa.String(length=40), nullable=True),
    sa.Column('venue', sa.String(length=20), nullable=False),
    sa.Column('listing_date', sa.Date(), nullable=True),
    sa.Column('delisting_date', sa.Date(), nullable=True),
    sa.Column('delisting_reason', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('ingested_at', database.types.UtcDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('security_uid', 'ticker', 'ticker_valid_from', name='uq_securities_uid_ticker_from')
    )
    with op.batch_alter_table('securities', schema=None) as batch_op:
        batch_op.create_index('ix_securities_ticker_valid', ['ticker', 'ticker_valid_from', 'ticker_valid_to'], unique=False)
        batch_op.create_index('ix_securities_uid', ['security_uid'], unique=False)

    op.create_table('universe_membership',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('universe_slug', sa.String(length=64), nullable=False),
    sa.Column('security_uid', sa.String(length=64), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('member_from', sa.Date(), nullable=False),
    sa.Column('member_to', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('known_at_utc', database.types.UtcDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('universe_slug', 'security_uid', 'member_from', name='uq_universe_membership_slug_uid_from')
    )
    with op.batch_alter_table('universe_membership', schema=None) as batch_op:
        batch_op.create_index('ix_universe_membership_slug_uid', ['universe_slug', 'security_uid'], unique=False)
        batch_op.create_index('ix_universe_membership_slug_window', ['universe_slug', 'member_from', 'member_to'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('universe_membership', schema=None) as batch_op:
        batch_op.drop_index('ix_universe_membership_slug_window')
        batch_op.drop_index('ix_universe_membership_slug_uid')

    op.drop_table('universe_membership')
    with op.batch_alter_table('securities', schema=None) as batch_op:
        batch_op.drop_index('ix_securities_uid')
        batch_op.drop_index('ix_securities_ticker_valid')

    op.drop_table('securities')
    op.drop_table('price_snapshots')
    with op.batch_alter_table('price_bars', schema=None) as batch_op:
        batch_op.drop_index('ix_price_bars_uid_date')
        batch_op.drop_index('ix_price_bars_date')

    op.drop_table('price_bars')
    with op.batch_alter_table('corporate_actions', schema=None) as batch_op:
        batch_op.drop_index('ix_corporate_actions_uid_date')

    op.drop_table('corporate_actions')
    # ### end Alembic commands ###
