"""
Ticker universe — S&P 500 constituents (auto-generated).
Last updated: 2026-02-21
Sector assignments from GICS classification.
Regenerate with: python scripts/update_sp500.py
"""

UNIVERSE = {
    # Communication Services (23)
    "CHTR": "Communication Services", "CMCSA": "Communication Services", "DIS": "Communication Services", "EA": "Communication Services",
    "FOX": "Communication Services", "FOXA": "Communication Services", "GOOG": "Communication Services", "GOOGL": "Communication Services",
    "LYV": "Communication Services", "META": "Communication Services", "MTCH": "Communication Services", "NFLX": "Communication Services",
    "NWS": "Communication Services", "NWSA": "Communication Services", "OMC": "Communication Services", "PSKY": "Communication Services",
    "T": "Communication Services", "TKO": "Communication Services", "TMUS": "Communication Services", "TTD": "Communication Services",
    "TTWO": "Communication Services", "VZ": "Communication Services", "WBD": "Communication Services",
    # Consumer Discretionary (48)
    "ABNB": "Consumer Discretionary", "AMZN": "Consumer Discretionary", "APTV": "Consumer Discretionary", "AZO": "Consumer Discretionary",
    "BBY": "Consumer Discretionary", "BKNG": "Consumer Discretionary", "CCL": "Consumer Discretionary", "CMG": "Consumer Discretionary",
    "CVNA": "Consumer Discretionary", "DASH": "Consumer Discretionary", "DECK": "Consumer Discretionary", "DHI": "Consumer Discretionary",
    "DPZ": "Consumer Discretionary", "DRI": "Consumer Discretionary", "EBAY": "Consumer Discretionary", "EXPE": "Consumer Discretionary",
    "F": "Consumer Discretionary", "GM": "Consumer Discretionary", "GPC": "Consumer Discretionary", "GRMN": "Consumer Discretionary",
    "HAS": "Consumer Discretionary", "HD": "Consumer Discretionary", "HLT": "Consumer Discretionary", "LEN": "Consumer Discretionary",
    "LOW": "Consumer Discretionary", "LULU": "Consumer Discretionary", "LVS": "Consumer Discretionary", "MAR": "Consumer Discretionary",
    "MCD": "Consumer Discretionary", "MGM": "Consumer Discretionary", "NCLH": "Consumer Discretionary", "NKE": "Consumer Discretionary",
    "NVR": "Consumer Discretionary", "ORLY": "Consumer Discretionary", "PHM": "Consumer Discretionary", "POOL": "Consumer Discretionary",
    "RCL": "Consumer Discretionary", "RL": "Consumer Discretionary", "ROST": "Consumer Discretionary", "SBUX": "Consumer Discretionary",
    "TJX": "Consumer Discretionary", "TPR": "Consumer Discretionary", "TSCO": "Consumer Discretionary", "TSLA": "Consumer Discretionary",
    "ULTA": "Consumer Discretionary", "WSM": "Consumer Discretionary", "WYNN": "Consumer Discretionary", "YUM": "Consumer Discretionary",
    # Consumer Staples (36)
    "ADM": "Consumer Staples", "BF-B": "Consumer Staples", "BG": "Consumer Staples", "CAG": "Consumer Staples",
    "CHD": "Consumer Staples", "CL": "Consumer Staples", "CLX": "Consumer Staples", "COST": "Consumer Staples",
    "CPB": "Consumer Staples", "DG": "Consumer Staples", "DLTR": "Consumer Staples", "EL": "Consumer Staples",
    "GIS": "Consumer Staples", "HRL": "Consumer Staples", "HSY": "Consumer Staples", "KDP": "Consumer Staples",
    "KHC": "Consumer Staples", "KMB": "Consumer Staples", "KO": "Consumer Staples", "KR": "Consumer Staples",
    "KVUE": "Consumer Staples", "LW": "Consumer Staples", "MDLZ": "Consumer Staples", "MKC": "Consumer Staples",
    "MNST": "Consumer Staples", "MO": "Consumer Staples", "PEP": "Consumer Staples", "PG": "Consumer Staples",
    "PM": "Consumer Staples", "SJM": "Consumer Staples", "STZ": "Consumer Staples", "SYY": "Consumer Staples",
    "TAP": "Consumer Staples", "TGT": "Consumer Staples", "TSN": "Consumer Staples", "WMT": "Consumer Staples",
    # Energy (22)
    "APA": "Energy", "BKR": "Energy", "COP": "Energy", "CTRA": "Energy",
    "CVX": "Energy", "DVN": "Energy", "EOG": "Energy", "EQT": "Energy",
    "EXE": "Energy", "FANG": "Energy", "HAL": "Energy", "KMI": "Energy",
    "MPC": "Energy", "OKE": "Energy", "OXY": "Energy", "PSX": "Energy",
    "SLB": "Energy", "TPL": "Energy", "TRGP": "Energy", "VLO": "Energy",
    "WMB": "Energy", "XOM": "Energy",
    # Financials (76)
    "ACGL": "Financials", "AFL": "Financials", "AIG": "Financials", "AIZ": "Financials",
    "AJG": "Financials", "ALL": "Financials", "AMP": "Financials", "AON": "Financials",
    "APO": "Financials", "ARES": "Financials", "AXP": "Financials", "BAC": "Financials",
    "BEN": "Financials", "BK": "Financials", "BLK": "Financials", "BRK-B": "Financials",
    "BRO": "Financials", "BX": "Financials", "C": "Financials", "CB": "Financials",
    "CBOE": "Financials", "CFG": "Financials", "CINF": "Financials", "CME": "Financials",
    "COF": "Financials", "COIN": "Financials", "CPAY": "Financials", "EG": "Financials",
    "ERIE": "Financials", "FDS": "Financials", "FIS": "Financials", "FISV": "Financials",
    "FITB": "Financials", "GL": "Financials", "GPN": "Financials", "GS": "Financials",
    "HBAN": "Financials", "HIG": "Financials", "HOOD": "Financials", "IBKR": "Financials",
    "ICE": "Financials", "IVZ": "Financials", "JKHY": "Financials", "JPM": "Financials",
    "KEY": "Financials", "KKR": "Financials", "L": "Financials", "MA": "Financials",
    "MCO": "Financials", "MET": "Financials", "MRSH": "Financials", "MS": "Financials",
    "MSCI": "Financials", "MTB": "Financials", "NDAQ": "Financials", "NTRS": "Financials",
    "PFG": "Financials", "PGR": "Financials", "PNC": "Financials", "PRU": "Financials",
    "PYPL": "Financials", "RF": "Financials", "RJF": "Financials", "SCHW": "Financials",
    "SPGI": "Financials", "STT": "Financials", "SYF": "Financials", "TFC": "Financials",
    "TROW": "Financials", "TRV": "Financials", "USB": "Financials", "V": "Financials",
    "WFC": "Financials", "WRB": "Financials", "WTW": "Financials", "XYZ": "Financials",
    # Healthcare (60)
    "A": "Healthcare", "ABBV": "Healthcare", "ABT": "Healthcare", "ALGN": "Healthcare",
    "AMGN": "Healthcare", "BAX": "Healthcare", "BDX": "Healthcare", "BIIB": "Healthcare",
    "BMY": "Healthcare", "BSX": "Healthcare", "CAH": "Healthcare", "CI": "Healthcare",
    "CNC": "Healthcare", "COO": "Healthcare", "COR": "Healthcare", "CRL": "Healthcare",
    "CVS": "Healthcare", "DGX": "Healthcare", "DHR": "Healthcare", "DVA": "Healthcare",
    "DXCM": "Healthcare", "ELV": "Healthcare", "EW": "Healthcare", "GEHC": "Healthcare",
    "GILD": "Healthcare", "HCA": "Healthcare", "HOLX": "Healthcare", "HSIC": "Healthcare",
    "HUM": "Healthcare", "IDXX": "Healthcare", "INCY": "Healthcare", "IQV": "Healthcare",
    "ISRG": "Healthcare", "JNJ": "Healthcare", "LH": "Healthcare", "LLY": "Healthcare",
    "MCK": "Healthcare", "MDT": "Healthcare", "MOH": "Healthcare", "MRK": "Healthcare",
    "MRNA": "Healthcare", "MTD": "Healthcare", "PFE": "Healthcare", "PODD": "Healthcare",
    "REGN": "Healthcare", "RMD": "Healthcare", "RVTY": "Healthcare", "SOLV": "Healthcare",
    "STE": "Healthcare", "SYK": "Healthcare", "TECH": "Healthcare", "TMO": "Healthcare",
    "UHS": "Healthcare", "UNH": "Healthcare", "VRTX": "Healthcare", "VTRS": "Healthcare",
    "WAT": "Healthcare", "WST": "Healthcare", "ZBH": "Healthcare", "ZTS": "Healthcare",
    # Industrials (79)
    "ADP": "Industrials", "ALLE": "Industrials", "AME": "Industrials", "AOS": "Industrials",
    "AXON": "Industrials", "BA": "Industrials", "BLDR": "Industrials", "BR": "Industrials",
    "CARR": "Industrials", "CAT": "Industrials", "CHRW": "Industrials", "CMI": "Industrials",
    "CPRT": "Industrials", "CSX": "Industrials", "CTAS": "Industrials", "DAL": "Industrials",
    "DE": "Industrials", "DOV": "Industrials", "EFX": "Industrials", "EME": "Industrials",
    "EMR": "Industrials", "ETN": "Industrials", "EXPD": "Industrials", "FAST": "Industrials",
    "FDX": "Industrials", "FIX": "Industrials", "FTV": "Industrials", "GD": "Industrials",
    "GE": "Industrials", "GEV": "Industrials", "GNRC": "Industrials", "GWW": "Industrials",
    "HII": "Industrials", "HON": "Industrials", "HUBB": "Industrials", "HWM": "Industrials",
    "IEX": "Industrials", "IR": "Industrials", "ITW": "Industrials", "J": "Industrials",
    "JBHT": "Industrials", "JCI": "Industrials", "LDOS": "Industrials", "LHX": "Industrials",
    "LII": "Industrials", "LMT": "Industrials", "LUV": "Industrials", "MAS": "Industrials",
    "MMM": "Industrials", "NDSN": "Industrials", "NOC": "Industrials", "NSC": "Industrials",
    "ODFL": "Industrials", "OTIS": "Industrials", "PAYC": "Industrials", "PAYX": "Industrials",
    "PCAR": "Industrials", "PH": "Industrials", "PNR": "Industrials", "PWR": "Industrials",
    "ROK": "Industrials", "ROL": "Industrials", "RSG": "Industrials", "RTX": "Industrials",
    "SNA": "Industrials", "SWK": "Industrials", "TDG": "Industrials", "TT": "Industrials",
    "TXT": "Industrials", "UAL": "Industrials", "UBER": "Industrials", "UNP": "Industrials",
    "UPS": "Industrials", "URI": "Industrials", "VLTO": "Industrials", "VRSK": "Industrials",
    "WAB": "Industrials", "WM": "Industrials", "XYL": "Industrials",
    # Materials (26)
    "ALB": "Materials", "AMCR": "Materials", "APD": "Materials", "AVY": "Materials",
    "BALL": "Materials", "CF": "Materials", "CRH": "Materials", "CTVA": "Materials",
    "DD": "Materials", "DOW": "Materials", "ECL": "Materials", "FCX": "Materials",
    "IFF": "Materials", "IP": "Materials", "LIN": "Materials", "LYB": "Materials",
    "MLM": "Materials", "MOS": "Materials", "NEM": "Materials", "NUE": "Materials",
    "PKG": "Materials", "PPG": "Materials", "SHW": "Materials", "STLD": "Materials",
    "SW": "Materials", "VMC": "Materials",
    # Real Estate (31)
    "AMT": "Real Estate", "ARE": "Real Estate", "AVB": "Real Estate", "BXP": "Real Estate",
    "CBRE": "Real Estate", "CCI": "Real Estate", "CPT": "Real Estate", "CSGP": "Real Estate",
    "DLR": "Real Estate", "DOC": "Real Estate", "EQIX": "Real Estate", "EQR": "Real Estate",
    "ESS": "Real Estate", "EXR": "Real Estate", "FRT": "Real Estate", "HST": "Real Estate",
    "INVH": "Real Estate", "IRM": "Real Estate", "KIM": "Real Estate", "MAA": "Real Estate",
    "O": "Real Estate", "PLD": "Real Estate", "PSA": "Real Estate", "REG": "Real Estate",
    "SBAC": "Real Estate", "SPG": "Real Estate", "UDR": "Real Estate", "VICI": "Real Estate",
    "VTR": "Real Estate", "WELL": "Real Estate", "WY": "Real Estate",
    # Technology (71)
    "AAPL": "Technology", "ACN": "Technology", "ADBE": "Technology", "ADI": "Technology",
    "ADSK": "Technology", "AKAM": "Technology", "AMAT": "Technology", "AMD": "Technology",
    "ANET": "Technology", "APH": "Technology", "APP": "Technology", "AVGO": "Technology",
    "CDNS": "Technology", "CDW": "Technology", "CIEN": "Technology", "CRM": "Technology",
    "CRWD": "Technology", "CSCO": "Technology", "CTSH": "Technology", "DDOG": "Technology",
    "DELL": "Technology", "EPAM": "Technology", "FFIV": "Technology", "FICO": "Technology",
    "FSLR": "Technology", "FTNT": "Technology", "GDDY": "Technology", "GEN": "Technology",
    "GLW": "Technology", "HPE": "Technology", "HPQ": "Technology", "IBM": "Technology",
    "INTC": "Technology", "INTU": "Technology", "IT": "Technology", "JBL": "Technology",
    "KEYS": "Technology", "KLAC": "Technology", "LRCX": "Technology", "MCHP": "Technology",
    "MPWR": "Technology", "MSFT": "Technology", "MSI": "Technology", "MU": "Technology",
    "NOW": "Technology", "NTAP": "Technology", "NVDA": "Technology", "NXPI": "Technology",
    "ON": "Technology", "ORCL": "Technology", "PANW": "Technology", "PLTR": "Technology",
    "PTC": "Technology", "Q": "Technology", "QCOM": "Technology", "ROP": "Technology",
    "SMCI": "Technology", "SNDK": "Technology", "SNPS": "Technology", "STX": "Technology",
    "SWKS": "Technology", "TDY": "Technology", "TEL": "Technology", "TER": "Technology",
    "TRMB": "Technology", "TXN": "Technology", "TYL": "Technology", "VRSN": "Technology",
    "WDAY": "Technology", "WDC": "Technology", "ZBRA": "Technology",
    # Utilities (31)
    "AEE": "Utilities", "AEP": "Utilities", "AES": "Utilities", "ATO": "Utilities",
    "AWK": "Utilities", "CEG": "Utilities", "CMS": "Utilities", "CNP": "Utilities",
    "D": "Utilities", "DTE": "Utilities", "DUK": "Utilities", "ED": "Utilities",
    "EIX": "Utilities", "ES": "Utilities", "ETR": "Utilities", "EVRG": "Utilities",
    "EXC": "Utilities", "FE": "Utilities", "LNT": "Utilities", "NEE": "Utilities",
    "NI": "Utilities", "NRG": "Utilities", "PCG": "Utilities", "PEG": "Utilities",
    "PNW": "Utilities", "PPL": "Utilities", "SO": "Utilities", "SRE": "Utilities",
    "VST": "Utilities", "WEC": "Utilities", "XEL": "Utilities",
}

# Sector ETFs for macro regime analysis
SECTOR_ETFS = {
    "XLK": "Technology",
    "XLF": "Financials",
    "XLV": "Healthcare",
    "XLY": "Consumer Discretionary",
    "XLP": "Consumer Staples",
    "XLI": "Industrials",
    "XLE": "Energy",
    "XLC": "Communication Services",
    "XLU": "Utilities",
    "XLRE": "Real Estate",
    "XLB": "Materials",
}
